import pytest

# is this proper parent access? may it error in non-relative execution location?
from ..main import log, parse_data, caclulate_differences

def test_calculation():
    ...

def test_log_error():
    ...

def test_log_unkown_severity():
    ...
    
# todo